language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4.1"
# command to install dependencies
install: "pip install -r requirements.txt --use-mirrors"
# command to run tests, e.g. python setup.py test
before_script:
  - python setup.py develop
script: nosetests
